import LeftSidebar from "@/components/LeftSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <main>
        <LeftSidebar/>
         {children}   
         <p className="text-white-1">Last page</p>
        </main>
  );
}
